apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: jeffjanderson
  - name: gitops_repository_name
    value: configrepo
  - name: gitops_user_name
    value: jeffjanderson
  - name: gitops_user_email
    value: jeff.j.anderson@gmail.com
  source:
    git:
      ref:
        branch: main
      url: https://github.com/jeffjanderson/tanzu-java-web-app
